# Build Stage
FROM  maven:3.8.7-openjdk-18 AS Build
WORKDIR /Build
COPY pom.xml .
RUN mvn dependency:go-offline
COPY src ./src
RUN mvn clean package -DskipTests

# Runtime stage
FROM amazoncorretto:17
ARG PROFILE = dev
ARG APP_VERSION=1.0.0


WORKDIR /app
COPY --from=build /build/target/book-network-*.jar /app/

EXPOSE 8088

ENV ACTIVE_PROFILE=${PROFILE}
ENV JAR_VERSION=${APP_VERSION}
CMD java -jar GithubAction-${JAR_VERSION}-SNAPSHOT.jar