  name: SpringBoot Prod Pipeline
  on:
    push:
      branches:
        - prod
      paths:
        - GithubAction/**
        - .github/workflows/**
        - 'deploy-pipeline-prod.yml'
        - 'docker/**'

  jobs:
    compile:
      runs-on: ubuntu-latest
      name: Compile Project
      steps:
        - name: Checkout Code
          uses: actions/checkout@v4
          with:
            fetch-depth: 0
        - name: setup JDK
          uses:  actions/setup-java@v4
          with:
            java-version: 17
            distribution: 'corretto'
        - name: Compile Project
          run: |
            mvn -B package --file pom.xml
    unit-tests:
      runs-on: ubuntu-latest
      name: Unit tests
      steps:
        - name: Checkout code
          uses: actions/checkout@v4
          with:
            fetch-depth: 0
        - name: Setup JDK
          uses: actions/setup-java@v4
          with:
            java-version: 17
            distribution: 'corretto'
        - name: Make mvnw executable
          run: chmod +x ./mvnw
        - name: Running unit Test
          run: |
            mvn -B package --file pom.xml
    build:
      runs-on: ubuntu-latest
      name: Build SpringBoot
      steps:
        - name: Checkout code
          uses: actions/checkout@v4
          with:
            fetch-depth: 0
        - name: Setup JDK
          uses: actions/setup-java@v4
          with:
            java-version: 17
            distribution: 'corretto'
        - name: Make mvnw executable
          run: chmod +x ./mvnw
        - name: Build Project
          run: |
            mvn -B package --file pom.xml
    
      
